routes/web.php
<?php

use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\LogoutController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth/login');
});

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware(['auth', 'checkRegistrationStep'])->name('dashboard');

Route::middleware(['auth'])->group(function () {
    Route::get('logout', [LogoutController::class, 'perform']);

    Route::resource('projects', ProjectController::class);
    Route::resource('applications', ApplicationController::class);

    Route::resource('profile', ProfileController::class);
    Route::get('projects/{project}/edit', [ProjectController::class, 'edit']);
    Route::get('projects/{project}/applicants', [ProjectController::class, 'show']);
    Route::post('projects/{project}/update-projects', [ProjectController::class, 'update']);
    Route::post('projects/{project}/destroy', [ProjectController::class, 'destroy']);
    Route::post('applications/{applications->id}/destroy', [ProjectController::class, 'destroy']);

    Route::get('projects/{project}/edit', [ProjectController::class, 'edit']);
    Route::get('profile', [RegisteredUserController::class, 'edit'])->name('profile');
    Route::put('profile', [RegisteredUserController::class, 'update'])->name('update-profile');
});




require __DIR__ . '/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    @section('css')
    <style>
        .header,
        .footer {
            overflow: hidden;
            position: fixed;
        }

        body {
            overflow-x: hidden;
            font-family: montserrat, sans-serif;
            font-style: normal;
            /* font-size: large; */
            height: 100%;

            background-image: url("../css/Images/3.jpg");
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            background-position: top;
            background-attachment: fixed;

        }
    </style>
    @endsection
    <x-slot name="header">

    </x-slot>


    {{-- Filter by academies --}}
    <div class="row p-0 d-flex">
        <div class="col-sm-3 pt-4 dashboard-offset" id="fixed">
            <p class="text-center bigger-text">In what field can you be amazing?</p>

            <div class="row d-flex justify-content-evenly academies-wrapper py-5">
                <div class="col-4 mx-3 radio-button-style">
                    <a class="text-decoration-none dashboard-academies-style text-center" href="/dashboard">
                        <div class="col-6  dashboard-academies-style text-center">
                            All
                        </div>
                    </a>
                </div>
                @foreach ($academies as $academy)
                <div class="col-4 mx-3 radio-button-style ">
                    <a class="text-decoration-none dashboard-academies-style text-center" href="?academy={{ $academy->id }}">
                        <div class="col-6 dashboard-academies-style text-center">
                            {{ $academy->name }}
                        </div>
                    </a>
                </div>

                @endforeach


            </div>
        </div>
        <div class="pt-2 pl-0 pr-0 row ">

            <p class="col-sm-3 offset-8 mt-3"><span class="d-inline"><img class="icons1 mt-4" src="../css/icons/3.png"></span>Checkout the latest projects</p>

            @foreach ($projects as $project)
            <div class="bg-white row card-style col-sm-7 m-project mt-5 mb-5 offset-4">
                <div class="col-4 position-relative">
                    <div class="image-wrapper mb-5">
                        <p class="image-style text-center">

                            <img class="img-rounded image-shape" src="{{ asset('storage/'.$project->user->image) }}" width="80px" alt="">

                        </p>
                    </div>


                    <p class="mt-4 text-center name-style">
                        {{ $project->user->name }} {{$project->user->surname}}
                    </p>
                    <p class="orange text-center">
                        @if($project->user->academy->name === "Backend Development")
                        I'm a Backend Developer
                        @elseif($project->user->academy->name === "Design")
                        I'm a Designer
                        @elseif($project->user->academy->name === "Frontend Development")
                        I'm a Frontend Developer
                        @elseif($project->user->academy->name === "Marketing")
                        I'm a Marketer
                        @elseif($project->user->academy->name === "Data Science")
                        I'm a Data Scientist
                        @elseif($project->user->academy->name === "QA")
                        I'm a QA Engineer
                        @elseif($project->user->academy->name === "UX/UI")
                        I'm a UX/UI Designer
                        @endif
                    </p>

                    <div class="mt-5 pt-5 parent-div">
                        <div class="child-div">
                            <p class="text-center font-size-small">
                                I am looking for:
                            </p>

                            <div class="row d-flex justify-content-center">
                                @php
                                $requirementsCounter = 0;
                                @endphp
                                @foreach ($project->requirements as $requirement)
                                @if($requirementsCounter<'4') <div class="half-circle col-3">
                                    @if($requirement->name === "Backend Development")
                                    Backend Dev
                                    @elseif($requirement->name === "Design")
                                    Designer
                                    @elseif($requirement->name === "Frontend Development")
                                    Frontend Dev
                                    @elseif($requirement->name === "Marketing")
                                    Marketer
                                    @elseif($requirement->name === "Data Science")
                                    Data
                                    @elseif($requirement->name === "QA")
                                    QA
                                    @elseif($requirement->name === "UX/UI")
                                    UX/UI
                                    @endif
                            </div>
                            @php
                            $requirementsCounter++;
                            @endphp
                            @endif

                            @endforeach
                        </div>

                    </div>

                </div>
            </div>
            <div class="col-8">
                <div class="counter-wrapper">
                    <p class="counter-style">
                        <span class="counter-number-font">{{ $project->applicants->count() }}</span>

                        <br>
                        Applicants
                    </p>
                </div>

                <p class="mt-4">
                    {{ $project->name }}
                </p>
                <p class="mt-4">
                    Project description:
                <p class="font-size-small">
                    {{ str_limit($project->description, 200, '') }}

                    @if (strlen($project->description) > 200)
                    <span id="dots">...</span>
                    <span id="more">{{ substr($project->description, 200) }}</span>
                    <button class="show-more-button" onclick="myFunction()" id="readMore">Show more</button>
                    @endif


                </p>
                </p>

                <div class="mt-4 mb-2 d-flex justify-content-sm-end align-items-end align-bottom">
                    @if ( in_array( $project->id, auth()->user()->applications()->pluck('projects.id')->toArray() ) )
                    <a class="mt-4 text-decoration-none apply-button-selected">
                        {{ __("I'M IN") }}
                    </a>
                    @else

                    <form name="myform" id="myform" action=" {{ route('applications.store', ['id' => $project->id]) }}" method="POST">
                        @csrf
                        <x-button id="submit" onClick="successMessage()" class=" mt-4 apply-button">
                            {{ __("I'M IN") }}
                        </x-button>
                        <div style="display: none;" id="application-successful" class="col-6 offset-3 alert alert-success fixed-top" role="alert">
                            <span> Succesfully applied to the project !</span>
                        </div>
                    </form>




                    @endif

                </div>
            </div>


        </div>

    </div>
    @endforeach
    </div>

    @section('js')
    <script>
        function successMessage() {
            document.getElementById("application-successful").style.display = "inline";
            setTimeout(function() {
                location.reload(true);
            }, 2000);

        }



        var dots = document.getElementById("dots");
        var moreText = document.getElementById("more");
        var btnText = document.getElementById("readMore");

        if (dots.style.display === "none") {
            dots.style.display = "inline";
            btnText.innerHTML = "Read more";
            moreText.style.display = "none";
        } else {
            dots.style.display = "none";
            btnText.innerHTML = "Read less";
            moreText.style.display = "inline";
        }
        $('.radio-btn').click(function() {
            $('.col').removeClass('text-white').css({
                'background-color': '#ffffff',
            });;
            $(this).filter(':checked').parent().addClass('text-white').css({
                'background-color': '#48695c',
            });
        });
    </script>
    @endsection


</x-app-layout>

resources/views/profile.blade.php
<x-app-layout>
    @section('css')
    <style>
        .header,
        .footer {
            overflow: hidden;
            position: fixed;
        }

        body {
            overflow-x: hidden;
            font-family: montserrat, sans-serif;
            font-style: normal;
            /* font-size: large; */
            height: 100%;

            background-color: #f6f6f6;

        }
    </style>
    @endsection
    <x-slot name="header">

    </x-slot>


    <form action="/profile/update-profile" method="POST" enctype="multipart/form-data">
        @csrf

        @method('PUT')
        <div class="row margin-create">
            <div class="col-5">

                <h3 class=" col mb-5">
                    {{ __('My Profile') }}
                </h3>

                <div class="row">
                    <div class="col-sm-6">
                        <div class="image-wrapper mb-2">
                            <p class="profile-image-style mt-2 text-center">
                                <img value="{{ $user->image }}" class="img-rounded image-shape" src="{{ asset('storage/'.$user->image) }}" width="80px" alt="">
                            </p>
                        </div>

                        <p class="row mt-3 profile-upload d-flex justify-content-center">
                            <x-input id="image" class="block mt-1 w-full" required type="file" name="image" capture />
                            <x-label class="label-text-size" for="image" value="Click here to upload an image" />
                        </p>
                    </div>
                    <div class="col-sm-6 mt-3">


                        <!-- Name -->
                        <x-input id="name" class="input-border-style block mt-1 w-full" type="name" name="name" value="{{ $user->name }}" required />


                        <!-- Surname -->
                        <x-input id="surname" class="input-border-style block mt-1 w-full" type="surname" name="surname" value="{{ $user->surname }}" required />


                        <!-- Email Address -->
                        <x-input id="email" class="input-border-style block mt-1 w-full" type="email" name="email" value="{{ $user->email }}" required />


                    </div>
                    <div class="col-12">
                        <div class="mt-4">
                            <label for="biography" :value="__('Biography')" class="biography-style">Biography
                                <textarea name="biography" id="biography" cols="30" rows="10" class="block rounded-md mt-1 w-full width-textarea fw-lighter" placeholder=" Lorem Ipsum is simply dummy text of the printing and typesetting industry unchanged.Lorem Ipsum is simply dummy text of the printing and typesetting industry unchanged" required name="biography" id="biography" cols="30" rows="10">{{ $user->biography }}
                                </textarea>
                        </div>
                    </div>
                </div>


            </div>
            <div class="col-7 justify-content-center mt-5 row">
                <div class="my-profile-skills text-center">

                    @foreach($skills as $skill)

                    <div class="profile-edit-button display-inline m-1 ">
                        <x-label class="justify-content-center skills-hover" for="skill{{ $skill->id }}" value="{{$skill->name}}" />
                        <x-input id="skill{{ $skill->id }}" class="block mt-1 w-full" type="checkbox" name="skills_ids[]" value="" />

                    </div>

                    @endforeach

                </div>

                <div class="d-flex mt-2 justify-content-sm-end align-items-end align-bottom">

                    <x-button class="ml-4 green button-style">
                        {{ __('EDIT') }}
                    </x-button>
                </div>

            </div>

        </div>




    </form>
    <form action="{{ route('logout') }}" method="post">
        @csrf
        <button class="btn btn-danger logout-button">Logout</button>

    </form>
    @section('js')
    <script>
        function myFunction() {
            var dots = document.getElementById("dots");
            var moreText = document.getElementById("more");
            var btnText = document.getElementById("readMore");

            if (dots.style.display === "none") {
                dots.style.display = "inline";
                btnText.innerHTML = "Read more";
                moreText.style.display = "none";
            } else {
                dots.style.display = "none";
                btnText.innerHTML = "Read less";
                moreText.style.display = "inline";
            }
        }
    </script>
    @endsection
</x-app-layout>