routes/web.php
<?php

use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\LogoutController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth/login');
});

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware(['auth', 'checkRegistrationStep'])->name('dashboard');

Route::middleware(['auth'])->group(function () {
    Route::get('logout', [LogoutController::class, 'perform']);

    Route::resource('projects', ProjectController::class);
    Route::resource('applications', ApplicationController::class);

    Route::resource('profile', ProfileController::class);
    Route::get('projects/{project}/edit', [ProjectController::class, 'edit']);
    Route::get('projects/{project}/applicants', [ProjectController::class, 'show']);
    Route::post('projects/{project}/update-projects', [ProjectController::class, 'update']);
    Route::post('projects/{project}/destroy', [ProjectController::class, 'destroy']);
    Route::post('applications/{applications->id}/destroy', [ProjectController::class, 'destroy']);

    Route::get('projects/{project}/edit', [ProjectController::class, 'edit']);
    Route::get('profile', [RegisteredUserController::class, 'edit'])->name('profile');
    Route::put('profile', [RegisteredUserController::class, 'update'])->name('update-profile');
});




require __DIR__ . '/auth.php';

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Project extends Model
{
    use HasFactory, SoftDeletes;



    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function requirements()
    {
        return $this->belongsToMany(Academy::class, 'academies_projects');
    }

    public function applicants()
    {
        return $this->belongsToMany(User::class, 'projects_users');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Academy;
use App\Models\Project;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Auth\RegisteredUserController;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = auth()->user()->projects()->latest()->get();
        return view('pages.projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $academies = Academy::all();

        return view('pages.projects.create', compact('academies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $user = auth()->user();

        $project = $user->projects()->create([
            'name' => $request->name,
            'description' => $request->description,
        ]);

        $project->requirements()->attach($request->academy_id);

        return redirect()->route('projects.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show($project)
    {
        $user = User::all();
        $academies = Academy::all();
        $applicants = auth()->user()->projects()->latest()->get();
        return view('pages.projects.applicants')->with('project', Project::find($project));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit($projectid)
    {
        $academies = Academy::all();
        $project = Project::find($projectid);
        return view('pages.projects.edit', compact('project', 'academies'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update($projectid)
    {

        $data = request()->all();
        $project = Project::find($projectid);

        $project->name = $data['name'];
        $project->description = $data['description'];
        $project->save();
        return redirect('/projects');
    }

    /** 
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy($projectid)

    {
        $project = Project::find($projectid);
        $project->delete();
        return redirect('/projects');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/pages/projects/applicants.blade.php
<x-app-layout>
    @section('css')
    <style>
        .header,
        .footer {
            overflow: hidden;
            position: fixed;
        }

        body {
            overflow-x: hidden;
            font-family: montserrat, sans-serif;
            font-style: normal;
            /* font-size: large; */
            height: 100%;
            background-color: #f6f6f6;

        }
    </style>
    @endsection
    <x-slot name="header">
        <h6 class="">
        </h6>
    </x-slot>
    {{-- List all projects created by the logged in user --}}
    <div class="row">
        <div class="col-10 offset-1 mb-4">
            <h3>{{ $project->name }} Applicants</h3>
            <h5 class="d-inline">Choose your teamates </h5><img class="icons2 d-inline" src="/css/icons/4.png" alt="">
        </div>
    </div>
    <div class="row d-flex mt-5">
        <div class="col-8 mt-5 d-flex justify-content-around offset-2">
            @foreach($project->applicants as $applicant)

            <div class="col-4 m-1 text-center bg-white applicants-card ">
                <div class="image-wrapper mb-5">
                    <p class="image-style-profile text-center">
                        <img class="img-rounded image-shape" src="{{ asset('storage/'.$applicant->image) }}" width="80px" alt="">
                    </p>
                </div>
                <h5 class="mt-5">{{$applicant->name}}</h5>
                <p class="orange">{{$applicant->academy->name}}</p>
                <p class="font-size-small">{{$applicant->email}}</p>
                <p class="message-font">{{$applicant->biography}}</p>

                <img class="icon_plus mb-3" src="/css/icons/1.png" alt="">
            </div>
            @endforeach

        </div>


    </div>


    @section('js')
    <script>
        function myFunction() {
            var dots = document.getElementById("dots");
            var moreText = document.getElementById("more");
            var btnText = document.getElementById("readMore");

            if (dots.style.display === "none") {
                dots.style.display = "inline";
                btnText.innerHTML = "Read more";
                moreText.style.display = "none";
            } else {
                dots.style.display = "none";
                btnText.innerHTML = "Read less";
                moreText.style.display = "inline";
            }
        }
    </script>
    @endsection

</x-app-layout>

resources/views/pages/projects/create.blade.php
<x-app-layout>
    @section('css')
    <style>
        body {
            overflow: hidden;
            font-family: montserrat, sans-serif;
            font-style: normal;
            font-size: large;
            background-color: #f6f6f6;
        }

        .title-text-size {
            font-size: 55px;

        }
    </style>
    @endsection
    <x-slot name="header">

    </x-slot>
    {{-- List all projects by loged in user --}}



    <form action="{{ route('projects.store') }}" method="post">
        @csrf
        <div class="row margin-create">
            <div class="col-6">

                <h3 class="col mb-5">
                    {{ __('New Project') }}
                </h3>

                <div>
                    <input id="name" class=" input-border-style bg-transparent block mt-1 " type="text" name="name" :value="old('name')" required autofocus placeholder="Name of project">
                </div>


                <div class="mt-4">
                    <label for="description" :value="__('Description')" class="biography-style">Description of project
                        <textarea name="description" id="description" cols="30" rows="10" class="block rounded-md mt-1 w-full width-textarea fw-lighter" placeholder=" Lorem Ipsum is simply dummy text of the printing and typesetting industry unchanged.Lorem Ipsum is simply dummy text of the printing and typesetting industry unchanged" required name="biography" id="biography" cols="30" rows="10"></textarea>
                </div>
            </div>

            <div class="col-6 justify-content-center row">
                <div class="mb-5">
                    <x-label class="h3" :value="__('What I need')" />
                </div>
                @foreach ($academies as $academy)


                <x-label for="academy{{ $academy->id }}" class="col-3 checkbox-button text-center radio-button-style justify-content-center ">
                    <x-input id="academy{{ $academy->id }}" class="block w-full" type="checkbox" name="academy_id[]" value="{{ $academy->id }}" />
                    <div class="d-flex justify-content-center text-align-middle">
                        <span class="span-text-center">{{$academy->name}}</span>
                    </div>
                </x-label>

                @endforeach
            </div>

        </div>

        <div class="d-flex col-11 academies-button-style justify-content-sm-end align-items-end items-center">
            <x-button class="green button-style">
                {{ __('Create') }}
            </x-button>
        </div>

    </form>
    </div>



</x-app-layout>

resources/views/pages/projects/edit.blade.php
<x-app-layout>
    @section('css')
    <style>
        body {
            overflow: hidden;
            font-family: montserrat, sans-serif;
            font-style: normal;
            font-size: large;
            background-color: #f6f6f6;
        }

        .title-text-size {
            font-size: 55px;

        }
    </style>
    @endsection
    <x-slot name="header">

    </x-slot>
    {{-- List all projects by loged in user --}}



    <form action="/projects/{{$project->id}}/update-projects" method="post">
        @csrf
        <div class="row margin-create">
            <div class="col-6">

                <h3 class="col mb-5">
                    {{ __('Edit Project') }}
                </h3>

                <div>
                    <input id="name" class=" input-border-style bg-transparent block mt-1 " type="text" name="name" value="{{$project->name}}" required autofocus>
                </div>


                <div class="mt-4">
                    <label for="description" :value="__('Description')" class="biography-style">Description of project
                        <textarea name="description" id="description" cols="30" rows="10" class="block rounded-md mt-1 w-full width-textarea fw-lighter" placeholder=" Lorem Ipsum is simply dummy text of the printing and typesetting industry unchanged.Lorem Ipsum is simply dummy text of the printing and typesetting industry unchanged" required name="biography" id="biography" cols="30" rows="10">{{$project->description}}</textarea>
                </div>
            </div>

            <div class="col-6 justify-content-center row">
                <div class="mb-5">
                    <x-label class="h3" :value="__('What I need')" />
                </div>
                @foreach ($academies as $academy)

                <div class="col-3 text-center checkbox-button radio-button-style">
                    <x-label class="justify-content-center skills-hover" for="academy{{ $academy->id }}" value="{{ $academy->name }}" />

                    <x-input id="academy{{ $academy->id }}" class="block w-full" type="checkbox" name="academy_id[]" value="{{ $academy->id }}" />
                </div>

                @endforeach
            </div>

        </div>

        <div class="d-flex col-11 academies-button-style justify-content-sm-end align-items-end items-center">
            <x-button class="green button-style">
                {{ __('Update') }}
            </x-button>
        </div>

    </form>
    </div>



</x-app-layout>

resources/views/pages/projects/index.blade.php
<x-app-layout>
    @section('css')
    <style>
        .header,
        .footer {
            overflow: hidden;
            position: fixed;
        }

        body {
            overflow-x: hidden;
            font-family: montserrat, sans-serif;
            font-style: normal;
            /* font-size: large; */
            height: 100%;
            background-image: url("../css/Images/4.jpg");
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            background-position: top;
            background-attachment: fixed;
        }
    </style>
    @endsection
    <x-slot name="header">
        <h6 class="">
        </h6>
    </x-slot>
    {{-- List all projects created by the logged in user --}}
    <div class="row">
        <div class="col-10 offset-1 mb-4">
            <h6>Have new idea to make the world better?</h6>
            <h3><a class="text-decoration-none text-black ml-5" href="{{ route('projects.create') }}">Create new project
                    <img class="icons" src="../css/icons/1.png" alt="">
                </a>

            </h3>
        </div>
    </div>
    <div class="row d-flex">
        @foreach ($projects as $project)
        <div class="row my-projects-card">
            <div class="row bg-white  card-style my-5 col-8 offset-2">
                <div class="col-4">
                    <div class="col-4 position-relative">
                        <div class="image-wrapper mb-5">
                            <p class="image-style text-center">

                                <img class="img-rounded image-shape" src="{{ asset('storage/'.$project->user->image) }}" width="80px" alt="">


                            </p>
                        </div>
                    </div>

                    <p class="mt-4 text-center name-style">
                        {{ $project->user->name }}
                        {{$project->user->surname}}
                    </p>
                    <p class=" orange text-center">
                        @if($project->user->academy->name === "Backend Development")
                        I'm a Backend Developer
                        @elseif($project->user->academy->name === "Design")
                        I'm a Designer
                        @elseif($project->user->academy->name === "Frontend Development")
                        I'm a Frontend Developer
                        @elseif($project->user->academy->name === "Marketing")
                        I'm a Marketer
                        @elseif($project->user->academy->name === "Data Science")
                        I'm a Data Scientist
                        @elseif($project->user->academy->name === "QA")
                        I'm a QA Engineer
                        @elseif($project->user->academy->name === "UX/UI")
                        I'm a UX/UI Designer



                        @endif
                    </p>

                    <div class="mt-5 pt-5">
                        <p class="text-center font-size-small">
                            I am looking for:
                        </p>

                        <div class="row d-flex the-position justify-content-center">
                            @php
                            $requirementsCounter = 0;
                            @endphp
                            @foreach ($project->requirements as $requirement)
                            @if($requirementsCounter<4) <div class="half-circle col-3">
                                @if($requirement->name === "Backend Development")
                                Backend Dev
                                @elseif($requirement->name === "Design")
                                Designer
                                @elseif($requirement->name === "Frontend Development")
                                Frontend Dev
                                @elseif($requirement->name === "Marketing")
                                Marketer
                                @elseif($requirement->name === "Data Science")
                                Data
                                @elseif($requirement->name === "QA")
                                QA
                                @elseif($requirement->name === "UX/UI")
                                UX/UI
                                @endif
                        </div>
                        @php
                        $requirementsCounter++;
                        @endphp
                        @endif

                        @endforeach

                    </div>
                </div>
            </div>
            <div class="col-8">
                <a href="/projects/{{$project->id}}/applicants">
                    <div class="counter-wrapper">
                        <p class="counter-style">
                            <span class="counter-number-font">{{ $project->applicants->count() }}</span>

                            <br>
                            Applicants
                        </p>
                    </div>
                </a>

                <p class="mt-4">
                    {{ $project->name }}
                </p>
                <p class="mt-4">
                    Project description:
                <p class="font-size-small">
                    {{ str_limit($project->description, 400, '') }}

                    @if (strlen($project->description) > 400)
                    <span id="dots">...</span>
                    <span id="more">{{ substr($project->description, 200) }}</span>
                    <button class="show-more-button" onclick="myFunction()" id="readMore">Read more</button>
                    @endif


                </p>
                </p>
            </div>
        </div>
        <div class="col-1 icon-wrapper">
            <a href="/projects/{{$project->id}}/edit"><img class="icons mt-5" src="../css/icons/8.png"></a>

            <form action="/projects/{{$project->id}}/destroy" method="POST">
                @csrf
                <x-button class="delete-button"><img class="icons mt-2" src="../css/icons/7.png"></x-button>
            </form>

        </div>
    </div>

    @endforeach

    @section('js')
    <script>
        function myFunction() {
            var dots = document.getElementById("dots");
            var moreText = document.getElementById("more");
            var btnText = document.getElementById("readMore");

            if (dots.style.display === "none") {
                dots.style.display = "inline";
                btnText.innerHTML = "Read more";
                moreText.style.display = "none";
            } else {
                dots.style.display = "none";
                btnText.innerHTML = "Read less";
                moreText.style.display = "inline";
            }
        }
    </script>
    @endsection

</x-app-layout>

resources/views/pages/projects/navigation.blade.php
@section('css')
<style>
    body {
        font-family: montserrat, sans-serif;
        font-style: normal;
        font-weight: 700;
        /* font-size: large; */

    }
</style>
@endsection

<nav class="navbar">
    <div class="container-fluid">
        <a class="navbar-brand" href="/dashboard">
            <h4 class="text-black logo d-block d-flex px-4 text-uppercase">brainster<span class="text-secondary text-uppercase">preneurs</span></h4>
        </a>

        <a href="/projects">
            <div style="width:50px; height:50px; margin-right:50px; background-color:black;  border-radius:50%" class="d-flex align-middle justify-content-center">
            </div>
        </a>

        <div class="bg-trasparent">
            <x-dropdown>
                <x-slot name="trigger">
                    <button class="d-flex border-none">
                        <div>{{ Auth::user()->name }}</div>
                        <svg class="" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                        </svg>
                    </button>
                </x-slot>

                <!-- <x-slot name="content">
                    <!-- Authentication -->
                <form class="bg-trasparent" method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-dropdown-link class="bg-transparent" :href="route('logout')" onclick="event.preventDefault();
                                                this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-dropdown-link>
                </form>
                </x-slot> -->
            </x-dropdown>
        </div>
    </div>

</nav>

<div class="col-sm-12 align-items-center orange-span-style">
    <p class="orange-span-full"></p>
</div>